version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: msvc_usuarios
    restart: always
    networks:
      - spring
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msvc_cursos
    restart: always
    networks:
      - spring
  usuarios-mcrsvc:
    container_name: usuarios-mcrsvc
    build:
      context: ./
      dockerfile: ./usuarios-mcrsvc/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./usuarios-mcrsvc/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  mcsvc-cursos:
    container_name: mcsvc-cursos
    build:
      context: ./
      dockerfile: ./mcsvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./mcsvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres
      - usuarios-mcrsvc
    restart: always

networks:
  spring:
